module.exports = [
    {
        name:'cookie研究',
        iconname:'icon-mine',
        show:true,
        url:'/personalmes',
    },
    {
        name:'项目经验',
        iconname:'icon-createtask',
        show:false,
        url:'/projectexp',
    },
    {
        name:'高德地图',
        iconname:'icon-other',
        show:false,
        url:'/reserve1',
    },
    {
        name:'回调函数',
        iconname:'icon-other',
        show:false,
        url:'/reserve2',
    },
    {
        name:'call方法',
        iconname:'icon-other',
        show:false,
        url:'/reserve3',
    },
    {
        name:'h5上传研究',
        iconname:'icon-other',
        show:false,
        url:'/reserve4',
    },
     {
        name:'富文本',
        iconname:'icon-other',
        show:false,
        url:'/reserve5',
    },
    {
        name:'promise',
        iconname:'icon-other',
        show:false,
        url:'/reserve6',
    },
]