module.exports = [
    {
        name:'个人信息',
        url:'/personalmes',
    },
    {
        name:'项目经验',
        url:'/projectexp',
    },
    {
        name:'预留1',
        url:'/reserve1',
    },
    {
        name:'预留2',
        url:'/reserve2',
    },
    {
        name:'预留3',
        url:'/reserve3',
    },
    {
        name:'预留4',
        url:'/reserve4',
    },
]